# Generated by Django 4.2.3 on 2023-08-29 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_alter_certificate_certifying_institution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certifyinginstitution",
            name="url",
            field=models.URLField(max_length=500),
        ),
    ]
