# Generated by Django 4.2.3 on 2023-08-29 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_alter_certifyinginstitution_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
